INPUT:
  SIZE: (32, 32)
  TRANSFORMS: ['random_flip', 'random_crop', 'normalize']
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASET:
  NAME: 'CIFAR10C'
  CIFAR_C_TYPE: 'brightness'
  CIFAR_C_LEVEL: 1

MODEL:
  BACKBONE:
    NAME: 'wide_resnet_16_4'